pipelines:
   default:
      - step:
          script:
             - git add <changed files>
             - git commit -m "[skip ci] Updates added via Bitbucket Pipelines deploy"
             - git push
