pipelines:
  default:
    - step:
        script:
          - echo "This script runs on all branches that don't have any specific pipeline assigned in 'branches'."
  branches:
    main:
      - step:
          script:
            - echo "This script runs only on commit to the main branch."
    feature/*:
      - step:
          script:
            - echo "This script runs only on commit to branches with names that match the feature/* pattern."
