- step:
    name: SonarCloud
    script:
     - pipe: sonarsource/sonarcloud-scan:2.0.0
          variables:
            SONAR_TOKEN: $SONAR_TOKEN
            EXTRA_ARGS: -Dsonar.projectDescription=\"Project with sonarcloud-scan pipe\" -Dsonar.eslint.reportPaths=\"report.json\"
            SONAR_SCANNER_OPTS: -Xmx512m
            DEBUG: "true"
