script:
  - pipe: atlassian/bitbucket-upload-file:0.7.1
    variables:
      BITBUCKET_USERNAME: $BITBUCKET_USERNAME
      BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
      FILENAME: 'package.json'
      ACCOUNT: $PROJECT_ACCOUNT
      REPOSITORY: $ALTERNATE_REPO
